### ISSUE TITLE
F-Droid app crashing without gplay services

### ISSUE THREAD

**Issue by klinzo** [digitalfabrik/ehrenamtskarte#495]
**Describe the bug**
The app installed from F-Droid always crashes directly on startup. The app is not usable at all.

**To Reproduce**
1. No google play services
2. Install app from F-Droid
3. Open app
4. See app crashing

**Expected behavior**
App does not crash.

**Smartphone (please complete the following information):**
 - Device: Xiaomi Mi Mix 2
 - OS: Android 11(Lineage OS 18.1)
 - Version: 2.1.1

**Additional context**
Stacktrace:
> Launching lib/main_staging.dart on Mi MIX 2 in debug mode...
Running Gradle task 'assembleDebug'...
✓  Built build/app/outputs/flutter-apk/app-debug.apk.
Installing build/app/outputs/flutter-apk/app.apk...
Debug service listening on ws://127.0.0.1:34791/-QMl8kC6p8w=/ws
Syncing files to device Mi MIX 2...
I/te.bayern.flos(12289): WaitForGcToComplete blocked RunEmptyCheckpoint on ProfileSaver for 12.411ms
I/Gralloc4(12289): mapper 4.x is not supported
W/Gralloc3(12289): mapper 3.x is not supported
E/AndroidRuntime(12289): FATAL EXCEPTION: main
E/AndroidRuntime(12289): Process: app.ehrenamtskarte.bayern.floss, PID: 12289
E/AndroidRuntime(12289): java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/common/GoogleApiAvailability;
E/AndroidRuntime(12289): 	at com.baseflow.geolocator.location.GeolocationManager.isGooglePlayServicesAvailable(GeolocationManager.java:79)
E/AndroidRuntime(12289): 	at com.baseflow.geolocator.location.GeolocationManager.createLocationClient(GeolocationManager.java:73)
E/AndroidRuntime(12289): 	at com.baseflow.geolocator.location.GeolocationManager.isLocationServiceEnabled(GeolocationManager.java:46)
E/AndroidRuntime(12289): 	at com.baseflow.geolocator.MethodCallHandlerImpl.onIsLocationServiceEnabled(MethodCallHandlerImpl.java:139)
E/AndroidRuntime(12289): 	at com.baseflow.geolocator.MethodCallHandlerImpl.onMethodCall(MethodCallHandlerImpl.java:62)
E/AndroidRuntime(12289): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/AndroidRuntime(12289): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:84)
E/AndroidRuntime(12289): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:865)
E/AndroidRuntime(12289): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/AndroidRuntime(12289): 	at android.os.MessageQueue.next(MessageQueue.java:335)
E/AndroidRuntime(12289): 	at android.os.Looper.loop(Looper.java:183)
E/AndroidRuntime(12289): 	at android.app.ActivityThread.main(ActivityThread.java:7664)
E/AndroidRuntime(12289): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(12289): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/AndroidRuntime(12289): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
E/AndroidRuntime(12289): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.common.GoogleApiAvailability" on path: DexPathList[[zip file "/data/app/~~eUhF6dGgxadL-UhsIANeFQ==/app.ehrenamtskarte.bayern.floss-BnGqW7FtIYpgLaSYcWHcfQ==/base.apk"],nativeLibraryDirectories=[/data/app/~~eUhF6dGgxadL-UhsIANeFQ==/app.ehrenamtskarte.bayern.floss-BnGqW7FtIYpgLaSYcWHcfQ==/lib/arm64, /data/app/~~eUhF6dGgxadL-UhsIANeFQ==/app.ehrenamtskarte.bayern.floss-BnGqW7FtIYpgLaSYcWHcfQ==/base.apk!/lib/arm64-v8a, /system/lib64, /system/system_ext/lib64, /system/product/lib64, /vendor/lib64]]
E/AndroidRuntime(12289): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:207)
E/AndroidRuntime(12289): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
E/AndroidRuntime(12289): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
E/AndroidRuntime(12289): 	... 15 more
I/Process (12289): Sending signal. PID: 12289 SIG: 9
Lost connection to device.

**Comment by maxammann** [comment]
Only happens with microg though

**Comment by a-andre** [comment]
This should be fixed with flutter-geolocator 3.1.8 (https://github.com/Baseflow/flutter-geolocator/pull/1050).

**Comment by maxammann** [comment]
I'm not sure how important this is as we will probably be removed soonish from the f-droid store.

**Comment by IzzySoft** [comment]
@maxammann if you want me to re-establish the app in my repo, just provide the APK again (ideally attached to its corresponding release). I've kept the metadata, so it should be easy enough. Would mean an uninstall and re-install for those having installed it from F-Droid, though…

**Comment by maxammann** [comment]
> @maxammann if you want me to re-establish the app in my repo, just provide the APK again (ideally attached to its corresponding release) and let me know. I've kept the metadata, so it should be easy enough. Would mean an uninstall and re-install for those having installed it from F-Droid, though…

No need for that at this point. We havent yet decided yet whther we are publishing our current and future apps through F-Droid.

**Comment by IzzySoft** [comment]
OK, then `s/if/when/` :wink:  Should the need arise. Though it's be sad if a project dedicated to Ehrenamt would only be available via walled gardens and thus make it unavailable to some of us. Which is why I offer to take it into my repo as compromise.

**Comment by maxammann** [comment]
Lets continue here: https://github.com/digitalfabrik/entitlementcard/issues/549
